repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: ^tora/
      - id: end-of-file-fixer
        files: ^tora/
      - id: check-yaml
        files: ^tora/
      - id: check-added-large-files
        files: ^tora/
      - id: check-merge-conflict
        files: ^tora/
      - id: check-toml
        files: ^tora/
      - id: debug-statements
        files: ^tora/

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        files: ^tora/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^tora/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--max-line-length=88, --extend-ignore=E203,W503,D100,D101,D102,D103,D104,D105,D106,D107]
        files: ^tora/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports]
        files: ^tora/
